<a href="https://colab.research.google.com/github/theaok/hfgi/blob/main/hfgi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#---------------------------SETUP----------------------------------
#get useful libraries
import io, time, os, sys, re #basics
import zipfile, json, datetime, string   #string for annotating points in scatter
import urllib.request
import numpy as np #basic math
from statistics import * #stats

import matplotlib.pyplot as plt #import pylab as plt #apparently discouraged now:
 #https://stackoverflow.com/questions/11469336/what-is-the-difference-between-pylab-and-pyplot
 #https://www.tutorialspoint.com/matplotlib/matplotlib_pylab_module.htm

import pandas as pd
import pandas_datareader as pdr
from pandas_datareader import wb
from pandas.io.formats.style import Styler
#s4 = Styler(df4, uuid_len=0, cell_ids=False)

import urllib  #weird, guess need to have os and pandas imported for this to work  %TODO/LATER ditch it, its weird anyway, just use wget/curl

from google.colab import files

#import webbrowser

import seaborn as sns

from google.colab import data_table
data_table.enable_dataframe_formatter() #this enables spreadsheet view upon calling dataframe (without() )

#many tricks how to extend notebook functionality
#https://coderzcolumn.com/tutorials/python/list-of-useful-magic-commands-in-jupyter-notebook-lab
#will display all output not just last command
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#MAGICS and THEMES/STYLES: important! does affect not just shading/colors, but also fonts, spacing, etc
#(even if you only select default (v not selecting anything) [but does seem to work better if you do make explicit sleections])

###magics: https://ipython.readthedocs.io/en/stable/interactive/magics.html
#most essential setup for vis: it does affect vis! careful!! stick with inline, maybe notebook; others mostly for non-notebook, eg spyder environ
#https://jakevdp.github.io/PythonDataScienceHandbook/04.00-introduction-to-matplotlib.html recomends *inline*!
#show current one:
#%matplotlib
#%matplotlib --list
#interactive plots:
#%matplotlib notebook
#static images of your plot:
%matplotlib inline
#may play with this one and other magics (btw default is probably agg)
#%matplotlib nbagg
##https://www.marktechpost.com/2023/10/20/6-magic-commands-for-jupyter-notebooks-in-python-data-science/
#%%latex
#%ai
#%run
#%writefile
#%history -n

###themes/styles: https://matplotlib.org/stable/gallery/style_sheets/style_sheets_reference.html
#https://jakevdp.github.io/PythonDataScienceHandbook/04.11-settings-and-stylesheets.html
#https://matplotlib.org/stable/tutorials/introductory/customizing.html
#here more about art and style than under the hood functionality as with magics, explore and experiment
#many may find 'default' or seaborn ones more pleasing; my fav 'classic' is back from 90s ;)
#plt.style.available #list available styles :) may install more
#plt.style.use('default') # more delicate subtle than classic
plt.style.use('classic')  #  'seaborn-whitegrid' 'seaborn-white' 'seaborn-poster'
# btw: magics v theme/style sequence matters, eg if i specify classic style before inline magic, i wouldnt get grey bounding box im getting

#sometimes have to install library which you get from https://pypi.org/
#!pip install geopandas

import statsmodels.formula.api as sm

https://dataverse.harvard.edu/file.xhtml?fileId=13094135&version=3.1

using
flourishingCountyYear.csv

TODO invite some of the authors of the data start with
Iacus, Stefano Maria and if not ask to rec co-author

>>>see how many obs per county min if few collapse over yrs!
then just descriptive stats and map and pop den like in brian everett paper

In [3]:
df=pd.read_csv('https://rutgers.box.com/shared/static/l7f4uiev8ju8b6xho2w0tbeplqdkxfle.zip')

/tmp/ipykernel_2633/2070100474.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('https://rutgers.box.com/shared/static/l7f4uiev8ju8b6xho2w0tbeplqdkxfle.zip')

In [4]:
df.shape

(2340928, 11)

In [5]:
df.columns

Index(['variable', 'stat', 'stat_se', 'salience', 'ntweets', 'validtweets',
       'natweets', 'FIPS', 'county', 'StateCounty', 'year'],
      dtype='object')

In [11]:
df.head(15)

,variable,stat,stat_se,salience,ntweets,validtweets,natweets,FIPS,county,StateCounty,year
0,loneliness,NaN,NaN,0.00,1,0,1,36.00,119.00,36119,2010
1,charity,NaN,NaN,0.00,1,0,1,6.00,83.00,06083,2010
2,jobsat,-1.00,NaN,1.00,1,1,0,31.00,55.00,31055,2010
3,purpose,-1.00,NaN,1.00,1,1,0,31.00,55.00,31055,2010
4,optimism,1.00,NaN,1.00,1,1,0,55.00,79.00,55079,2010
5,drinkhealth,NaN,NaN,0.00,1,0,1,48.00,451.00,48451,2011
6,healthlim,1.00,NaN,0.50,2,1,1,34.00,17.00,34017,2011
7,volunteer,NaN,NaN,0.00,1,0,1,18.00,57.00,18057,2011
8,optimism,NaN,NaN,0.00,1,0,1,31.00,119.00,31119,2011
9,goodpromo,NaN,NaN,0.00,1,0,1,37.00,81.00,37081,2011
10,migmoodPos,NaN,NaN,0.00,1,0,1,8.00,35.00,08035,2011
11,drinkhealth,NaN,NaN,0.00,2,0,2,12.00,11.00,12011,2011
12,q2_0,1.00,NaN,1.00,1,1,0,12.00,109.00,12109,2011
13,energy,1.00,NaN,1.00,1,1,0,27.00,171.00,27171,2011
14,polvoice,NaN,NaN,0.00,3,0,3,12.00,86.00,12086,2011

In [13]:
pd.set_option('display.max_rows', None)
df.variable.value_counts() #lifesat for now

variable
loneliness       37873
charity          37873
jobsat           37873
purpose          37873
optimism         37873
drinkhealth      37873
healthlim        37873
volunteer        37873
goodpromo        37873
migmoodPos       37873
energy           37873
polvoice         37873
gratitude        37873
discrim          37873
delaygrat        37873
trusted          37873
lovedgod         37873
ptsd             37873
anxiety          37873
govapprove       37873
pain             37873
relcomfort       37873
empathy          37873
afterlife        37873
smokehealth      37873
suffering        37873
forgive          37873
relationships    37873
migmood          37873
corruption       37873
q3_0             37873
happiness        37873
q6_0             37873
innerpeace       37873
depression       37873
resilience       37873
selfesteem       37873
lifesat          37873
fearfuture       37873
vitality         37873
posfunct         37873
trust            37873
balance          37873
altruism         37873
belonging        37873
mastery          37873
believegod       37873
spiritpun        37873
relcrit          37873
finworry         37873
migmoodNeg       37873
hope             37873
q2_0             37872
q4_0             37872
q5_0             37872
q4_1             23521
q5_1             23004
q2_2             22922
q2_1             17197
q6_1             16695
q3_2             15311
q4_11            11843
q3_1             11514
q4_8             11206
q4_3             10159
q4_12             9655
q4_15             9237
q4_10             8158
q4_6              7940
q5_2              7561
q4_14             7425
q6_2              6022
q4_5              5965
q4_7              5709
q4_4              5650
q4_2              5555
q4_13             5380
q4_9              3699
q4_16             3338
q2_3              1807
q3_3              1443
Name: count, dtype: int64

In [10]:
pd.set_option('display.float_format', lambda x: f'{x:.2f}')
df.ntweets.describe()

count    2340928.00
mean       61449.18
std       386376.78
min            1.00
25%          208.00
50%         2129.00
75%        15517.25
max     32699771.00
Name: ntweets, dtype: float64

In [14]:
df = df[df['variable'] == 'lifesat']

In [17]:
pd.set_option('display.max_rows', None)
df.ntweets.describe()

count      37873.00
mean       69057.64
std       409042.14
min            1.00
25%          485.00
50%         3203.00
75%        19822.00
max     32699771.00
Name: ntweets, dtype: float64

In [23]:
df = df[df['ntweets'] > 500] #do note validtweets is as low as >65 and <100 for like 20obs
df.shape
df.year.value_counts()

(28265, 11)

year
2014    3101
2013    3079
2015    2945
2018    2595
2019    2551
2020    2468
2017    2465
2021    2370
2022    2257
2016    1977
2023    1617
2012     840
Name: count, dtype: int64

In [21]:
df.head(1000)

,variable,stat,stat_se,salience,ntweets,validtweets,natweets,FIPS,county,StateCounty,year
84,lifesat,-0.20,0.69,0.35,1101,367,734,28.00,67.00,28067,2012
779,lifesat,-0.20,0.09,0.37,82345,30352,51993,26.00,149.00,26149,2013
780,lifesat,-0.19,0.14,0.38,31628,11708,19920,39.00,135.00,39135,2013
781,lifesat,-0.19,0.11,0.37,68801,24905,43896,21.00,179.00,21179,2013
782,lifesat,-0.20,0.14,0.36,38191,13621,24570,22.00,75.00,22075,2013
783,lifesat,-0.18,0.14,0.36,37392,13199,24193,1.00,31.00,01031,2013
1111,lifesat,-0.20,0.35,0.37,5517,2005,3512,20.00,205.00,20205,2013
1112,lifesat,-0.18,0.25,0.36,10998,3992,7006,27.00,149.00,27149,2013
1113,lifesat,-0.20,0.13,0.35,45787,15985,29802,31.00,119.00,31119,2013
1114,lifesat,-0.13,0.29,0.38,7148,2579,4569,53.00,69.00,53069,2013
1673,lifesat,-0.11,0.19,0.36,44356,16158,28198,4.00,12.00,04012,2014
1674,lifesat,-0.15,0.07,0.36,419675,150776,268899,19.00,103.00,19103,2014
1675,lifesat,-0.15,0.12,0.37,90859,33821,57038,21.00,205.00,21205,2014
1676,lifesat,-0.21,0.53,0.37,2918,1067,1851,38.00,81.00,38081,2014
1677,lifesat,-0.09,0.12,0.37,78803,29069,49734,41.00,41.00,41041,2014
1678,lifesat,-0.09,0.09,0.36,155383,55510,99873,47.00,119.00,47119,2014
1679,lifesat,-0.07,0.60,0.37,2109,790,1319,46.00,61.00,46061,2014
1680,lifesat,-0.09,0.23,0.36,17949,6464,11485,47.00,173.00,47173,2014
1681,lifesat,-0.17,0.19,0.36,31166,11294,19872,51.00,195.00,51195,2014
1682,lifesat,-0.16,0.44,0.34,4418,1566,2852,55.00,77.00,55077,2014
1683,lifesat,0.05,0.72,0.27,1472,274,1198,8.00,61.00,08061,2014
1684,lifesat,-0.12,0.27,0.35,13430,4700,8730,20.00,181.00,20181,2014
1685,lifesat,-0.15,0.45,0.37,4463,1647,2816,21.00,189.00,21189,2014
2598,lifesat,-0.12,0.18,0.29,357817,123575,234242,26.00,65.00,26065,2015
2599,lifesat,0.03,0.25,0.29,32791,10795,21996,41.00,71.00,41071,2015
2600,lifesat,-0.11,0.21,0.28,155129,50918,104211,42.00,129.00,42129,2015
2601,lifesat,0.13,0.35,0.28,15595,4904,10691,50.00,25.00,50025,2015
2602,lifesat,-0.09,0.37,0.28,7250,2505,4745,54.00,103.00,54103,2015
2603,lifesat,-0.07,0.59,0.26,1780,565,1215,48.00,317.00,48317,2015
2604,lifesat,-0.09,0.23,0.29,31132,10873,20259,54.00,79.00,54079,2015
2605,lifesat,-0.00,0.45,0.28,3909,1253,2656,55.00,49.00,55049,2015
2606,lifesat,-0.02,0.35,0.27,8275,2843,5432,8.00,87.00,08087,2015
2607,lifesat,0.08,0.48,0.27,4643,1478,3165,53.00,47.00,53047,2015
2608,lifesat,-0.17,0.53,0.27,1894,620,1274,55.00,91.00,55091,2015
2609,lifesat,-0.04,0.53,0.34,3858,1321,2537,21.00,61.00,21061,2015
2829,lifesat,0.57,0.29,0.17,14938,2588,12350,51.00,41.00,51041,2016
2830,lifesat,0.34,0.51,0.11,6923,828,6095,2.00,290.00,02290,2016
2968,lifesat,0.56,0.78,0.15,954,144,810,53.00,17.00,53017,2016
3067,lifesat,0.65,0.39,0.19,5926,1150,4776,50.00,27.00,50027,2016
3068,lifesat,0.65,0.61,0.15,1240,203,1037,18.00,133.00,18133,2016
3070,lifesat,0.58,0.58,0.17,2651,451,2200,37.00,157.00,37157,2016
3071,lifesat,0.65,0.70,0.13,1089,147,942,29.00,117.00,29117,2016
3612,lifesat,0.62,0.33,0.24,9523,2310,7213,35.00,35.00,35035,2017
3613,lifesat,0.59,0.52,0.13,4737,615,4122,55.00,81.00,55081,2017
3614,lifesat,0.59,0.56,0.18,2380,419,1961,42.00,5.00,42005,2017
3615,lifesat,0.15,0.36,0.19,12861,2651,10210,51.00,790.00,51790,2017
3616,lifesat,0.66,0.65,0.13,1629,212,1417,20.00,99.00,20099,2017
3618,lifesat,0.64,0.51,0.17,3650,612,3038,48.00,221.00,48221,2017
3619,lifesat,0.59,0.45,0.18,6599,1183,5416,1.00,95.00,01095,2017
3620,lifesat,0.66,0.57,0.17,1313,224,1089,19.00,157.00,19157,2017
3621,lifesat,0.58,0.69,0.14,1853,250,1603,48.00,371.00,48371,2017
3622,lifesat,0.66,0.52,0.18,3314,633,2681,51.00,67.00,51067,2017
3970,lifesat,0.59,0.44,0.16,6322,1131,5191,27.00,97.00,27097,2017
4307,lifesat,-0.01,0.30,0.24,22957,6848,16109,1.00,77.00,01077,2018
4308,lifesat,0.01,0.19,0.29,1185039,368630,816409,6.00,75.00,06075,2018
4309,lifesat,-0.16,0.15,0.23,70331,23338,46993,28.00,35.00,28035,2018
4310,lifesat,-0.02,0.18,0.25,553515,157698,395817,36.00,103.00,36103,2018
4311,lifesat,-0.04,0.22,0.20,168850,46529,122321,37.00,51.00,37051,2018
4312,lifesat,-0.03,0.23,0.21,96490,26311,70179,33.00,9.00,33009,2018
4313,lifesat,-0.06,0.31,0.27,25885,7980,17905,12.00,17.00,12017,2018
4314,lifesat,0.16,0.32,0.21,21816,5145,16671,29.00,165.00,29165,2018
4315,lifesat,0.21,0.69,0.31,930,261,669,49.00,1.00,49001,2018
4701,lifesat,0.24,0.87,0.25,631,142,489,29.00,93.00,29093,2018
5196,lifesat,-0.10,0.37,0.30,7676,2334,5342,1.00,21.00,01021,2019
5197,lifesat,-0.08,0.55,0.27,3209,905,2304,19.00,67.00,19067,2019
5198,lifesat,-0.02,0.33,0.31,10886,3337,7549,29.00,127.00,29127,2019
5199,lifesat,-0.11,0.06,0.31,569592,175517,394075,40.00,143.00,40143,2019
5200,lifesat,-0.04,0.49,0.32,4906,1581,3325,45.00,23.00,45023,2019
5201,lifesat,-0.06,0.30,0.31,10938,3360,7578,49.00,51.00,49051,2019
5202,lifesat,-0.08,0.39,0.31,7904,2265,5639,48.00,499.00,48499,2019
5203,lifesat,-0.07,0.41,0.34,6239,2192,4047,54.00,1.00,54001,2019
5204,lifesat,-0.10,0.53,0.28,3762,1077,2685,13.00,91.00,13091,2019
5205,lifesat,-0.07,0.52,0.33,3649,1173,2476,21.00,115.00,21115,2019
5207,lifesat,0.16,0.65,0.31,1081,360,721,12.00,29.00,12029,2019
5841,lifesat,-0.21,0.24,0.33,20526,6719,13807,6.00,109.00,06109,2020
5842,lifesat,-0.08,0.61,0.21,3650,731,2919,16.00,37.00,16037,2020
5843,lifesat,-0.15,0.10,0.32,246932,77832,169100,35.00,53.00,35053,2020
5844,lifesat,-0.17,0.13,0.31,115834,35839,79995,42.00,129.00,42129,2020
5845,lifesat,-0.14,0.18,0.32,46103,14868,31235,51.00,800.00,51800,2020
5846,lifesat,-0.06,0.44,0.31,6791,2051,4740,48.00,73.00,48073,2020
5847,lifesat,-0.10,0.44,0.29,5776,1686,4090,29.00,1.00,29001,2020
5848,lifesat,0.19,0.71,0.36,1357,474,883,49.00,37.00,49037,2020
6506,lifesat,-0.12,0.43,0.30,7381,2050,5331,26.00,69.00,26069,2021
6507,lifesat,-0.07,0.19,0.28,55444,15354,40090,27.00,137.00,27137,2021
6508,lifesat,0.06,0.32,0.27,12515,3406,9109,27.00,35.00,27035,2021
6509,lifesat,-0.06,0.39,0.28,8921,2487,6434,36.00,105.00,36105,2021
6510,lifesat,-0.06,0.24,0.31,25594,7833,17761,37.00,31.00,37031,2021
6511,lifesat,-0.03,0.28,0.28,21620,6038,15582,40.00,17.00,40017,2021
6513,lifesat,-0.04,0.57,0.29,3188,948,2240,37.00,13.00,37013,2021
6514,lifesat,-0.01,0.49,0.26,5470,1449,4021,56.00,5.00,56005,2021
6515,lifesat,0.09,0.65,0.30,2556,750,1806,19.00,17.00,19017,2021
6516,lifesat,0.02,0.58,0.31,3194,1008,2186,37.00,47.00,37047,2021
7214,lifesat,-0.07,0.19,0.30,44219,13267,30952,13.00,113.00,13113,2022
7215,lifesat,0.03,0.17,0.28,53632,15264,38368,21.00,227.00,21227,2022
7216,lifesat,-0.02,0.36,0.28,11512,3229,8283,25.00,7.00,25007,2022
7217,lifesat,0.20,0.24,0.31,19243,6079,13164,37.00,125.00,37125,2022
7218,lifesat,0.31,0.30,0.28,18440,5151,13289,47.00,103.00,47103,2022
7219,lifesat,-0.05,0.53,0.28,4181,1168,3013,5.00,63.00,05063,2022
7220,lifesat,-0.03,0.69,0.27,2110,531,1579,36.00,123.00,36123,2022
7221,lifesat,0.01,0.44,0.28,6858,1937,4921,48.00,265.00,48265,2022
7222,lifesat,-0.25,0.55,0.31,2019,656,1363,12.00,13.00,12013,2022
7223,lifesat,0.06,0.53,0.23,5833,1349,4484,31.00,111.00,31111,2022
7224,lifesat,0.10,0.83,0.29,760,217,543,18.00,131.00,18131,2022
7225,lifesat,0.04,0.64,0.28,2587,761,1826,26.00,101.00,26101,2022
7616,lifesat,-0.17,0.73,0.28,1465,409,1056,13.00,189.00,13189,2022
7619,lifesat,-0.02,0.81,0.30,875,250,625,51.00,33.00,51033,2022
7690,lifesat,-0.13,0.78,0.30,918,251,667,54.00,91.00,54091,2022
8007,lifesat,-0.19,0.41,0.31,3715,1097,2618,18.00,43.00,18043,2023
8008,lifesat,-0.05,0.23,0.27,13093,3595,9498,20.00,177.00,20177,2023
8010,lifesat,-0.06,0.74,0.24,666,160,506,21.00,217.00,21217,2023
9247,lifesat,-0.17,0.43,0.34,3685,1267,2418,42.00,133.00,42133,2012
9249,lifesat,-0.05,0.75,0.34,820,285,535,37.00,125.00,37125,2012
9250,lifesat,0.01,0.67,0.32,1658,518,1140,8.00,13.00,08013,2012
9472,lifesat,-0.04,0.76,0.34,783,274,509,23.00,19.00,23019,2012
9546,lifesat,-0.08,0.78,0.33,575,200,375,55.00,35.00,55035,2012
9975,lifesat,-0.14,0.14,0.36,36133,12905,23228,18.00,99.00,18099,2013
9976,lifesat,-0.21,0.15,0.37,34577,12491,22086,1.00,13.00,01013,2013
9977,lifesat,-0.17,0.10,0.36,90702,32299,58403,51.00,3.00,51003,2013
9978,lifesat,-0.13,0.17,0.38,33819,12340,21479,33.00,3.00,33003,2013
9979,lifesat,-0.09,0.23,0.36,16831,6046,10785,47.00,103.00,47103,2013
9980,lifesat,-0.10,0.19,0.36,20103,7156,12947,13.00,187.00,13187,2013
10317,lifesat,-0.16,0.07,0.36,237903,85450,152453,4.00,27.00,04027,2013
10318,lifesat,0.02,0.10,0.33,112540,37323,75217,6.00,41.00,06041,2013
10319,lifesat,-0.10,0.61,0.37,769,275,494,8.00,109.00,08109,2013
10873,lifesat,-0.15,0.18,0.36,32519,11656,20863,12.00,27.00,12027,2014
10874,lifesat,-0.14,0.15,0.36,50711,18069,32642,13.00,299.00,13299,2014
10875,lifesat,-0.14,0.20,0.36,21766,7744,14022,17.00,41.00,17041,2014
10876,lifesat,-0.16,0.45,0.35,5185,1718,3467,20.00,77.00,20077,2014
10877,lifesat,-0.23,0.05,0.34,591424,202860,388564,22.00,17.00,22017,2014
10878,lifesat,-0.16,0.20,0.39,25021,9542,15479,26.00,143.00,26143,2014
10879,lifesat,-0.11,0.08,0.35,401508,140871,260637,29.00,47.00,29047,2014
10880,lifesat,-0.15,0.19,0.37,30571,11374,19197,35.00,39.00,35039,2014
10881,lifesat,-0.15,0.08,0.35,290896,103169,187727,36.00,7.00,36007,2014
10882,lifesat,-0.19,0.08,0.37,208698,75828,132870,42.00,85.00,42085,2014
10883,lifesat,-0.06,0.06,0.35,1938244,680200,1258044,47.00,37.00,47037,2014
10884,lifesat,-0.03,0.67,0.32,1361,448,913,2.00,70.00,02070,2014
10885,lifesat,-0.10,0.51,0.33,2400,783,1617,48.00,443.00,48443,2014
11830,lifesat,0.00,0.23,0.28,475396,152127,323269,1.00,73.00,01073,2015
11831,lifesat,-0.04,0.31,0.27,8587,2868,5719,20.00,149.00,20149,2015
11832,lifesat,-0.13,0.22,0.29,68031,23153,44878,39.00,23.00,39023,2015
11833,lifesat,0.01,0.33,0.30,12569,4344,8225,47.00,55.00,47055,2015
11834,lifesat,0.25,0.26,0.31,43863,14723,29140,49.00,43.00,49043,2015
11835,lifesat,-0.14,0.18,0.29,106497,34794,71703,51.00,740.00,51740,2015
11836,lifesat,-0.07,0.28,0.29,22982,7624,15358,13.00,179.00,13179,2015
11837,lifesat,0.13,0.76,0.26,1196,323,873,16.00,79.00,16079,2015
11838,lifesat,-0.01,0.62,0.29,1269,397,872,20.00,137.00,20137,2015
12055,lifesat,0.39,0.23,0.20,48039,9629,38410,10.00,3.00,10003,2016
12056,lifesat,0.49,0.38,0.18,7641,1489,6152,24.00,45.00,24045,2016
12271,lifesat,0.53,0.67,0.19,583,112,471,41.00,1.00,41001,2016
12272,lifesat,0.48,0.63,0.21,1949,401,1548,21.00,205.00,21205,2016
12273,lifesat,0.57,0.76,0.19,525,105,420,27.00,157.00,27157,2016
12274,lifesat,0.67,0.59,0.20,1542,320,1222,47.00,145.00,47145,2016
12276,lifesat,0.62,0.64,0.15,950,143,807,17.00,177.00,17177,2016
12278,lifesat,0.59,0.69,0.19,654,131,523,12.00,47.00,12047,2016
12838,lifesat,0.69,0.15,0.23,44908,10286,34622,12.00,5.00,12005,2017
12839,lifesat,0.60,0.67,0.13,1757,219,1538,20.00,85.00,20085,2017
12840,lifesat,0.43,0.48,0.17,6962,1175,5787,41.00,59.00,41059,2017
12841,lifesat,0.66,0.62,0.15,1910,270,1640,42.00,121.00,42121,2017
12842,lifesat,0.62,0.41,0.19,7776,1472,6304,37.00,87.00,37087,2017
12843,lifesat,0.29,0.72,0.21,2370,482,1888,36.00,95.00,36095,2017
12844,lifesat,0.56,0.41,0.18,7982,1410,6572,13.00,217.00,13217,2017
12845,lifesat,0.69,0.62,0.15,804,129,675,19.00,77.00,19077,2017
12847,lifesat,0.63,0.60,0.14,2567,370,2197,51.00,93.00,51093,2017
13208,lifesat,0.63,0.66,0.24,808,139,669,48.00,391.00,48391,2017
13243,lifesat,0.66,0.69,0.33,509,143,366,8.00,27.00,08027,2017
13538,lifesat,-0.01,0.20,0.25,223148,66320,156828,17.00,97.00,17097,2018
13539,lifesat,0.04,0.18,0.23,236385,64718,171667,27.00,123.00,27123,2018
13540,lifesat,0.08,0.59,0.24,1992,568,1424,28.00,139.00,28139,2018
13541,lifesat,0.03,0.30,0.24,26590,7220,19370,42.00,75.00,42075,2018
13542,lifesat,0.35,0.75,0.26,534,89,445,5.00,141.00,05141,2018
13543,lifesat,0.01,0.31,0.24,18903,5484,13419,18.00,91.00,18091,2018
13544,lifesat,0.03,0.47,0.29,3778,1191,2587,48.00,89.00,48089,2018
13545,lifesat,0.22,0.62,0.21,4245,764,3481,16.00,75.00,16075,2018
13547,lifesat,0.01,0.59,0.25,2871,787,2084,29.00,219.00,29219,2018
13549,lifesat,0.22,0.55,0.16,7515,1170,6345,18.00,23.00,18023,2018
13857,lifesat,0.18,0.57,0.20,3228,768,2460,46.00,135.00,46135,2018
13858,lifesat,0.05,0.73,0.27,756,227,529,47.00,111.00,47111,2018
13859,lifesat,0.08,0.51,0.22,3346,857,2489,46.00,127.00,46127,2018
14404,lifesat,-0.08,0.21,0.31,22002,6713,15289,1.00,51.00,01051,2019
14405,lifesat,-0.04,0.28,0.31,16814,5171,11643,5.00,33.00,05033,2019
14406,lifesat,-0.10,0.13,0.33,76377,25131,51246,6.00,89.00,06089,2019
14407,lifesat,-0.00,0.55,0.31,3115,962,2153,8.00,7.00,08007,2019
14408,lifesat,0.00,0.38,0.33,7490,2453,5037,21.00,217.00,21217,2019
14409,lifesat,-0.12,0.21,0.32,28914,9390,19524,37.00,99.00,37099,2019
14410,lifesat,-0.04,0.08,0.31,371348,115969,255379,47.00,65.00,47065,2019
14411,lifesat,-0.11,0.15,0.31,60734,19170,41564,53.00,75.00,53075,2019
14412,lifesat,-0.12,0.24,0.32,21774,6949,14825,35.00,61.00,35061,2019
14413,lifesat,-0.08,0.51,0.31,3931,1233,2698,26.00,105.00,26105,2019
14414,lifesat,-0.07,0.72,0.29,1110,332,778,54.00,87.00,54087,2019
14415,lifesat,-0.11,0.59,0.29,2560,752,1808,16.00,45.00,16045,2019
14416,lifesat,-0.01,0.58,0.30,3238,998,2240,29.00,135.00,29135,2019
15031,lifesat,-0.07,0.20,0.31,32744,10116,22628,8.00,37.00,08037,2020
15032,lifesat,-0.22,0.64,0.36,1195,442,753,13.00,5.00,13005,2020
15033,lifesat,-0.01,0.70,0.27,1510,401,1109,18.00,101.00,18101,2020
15034,lifesat,-0.12,0.13,0.30,125599,37661,87938,19.00,113.00,19113,2020
15035,lifesat,-0.18,0.30,0.33,13294,4392,8902,22.00,115.00,22115,2020
15036,lifesat,-0.08,0.70,0.33,1973,637,1336,48.00,123.00,48123,2020
15037,lifesat,-0.12,0.24,0.33,21573,7188,14385,48.00,213.00,48213,2020
15038,lifesat,-0.16,0.21,0.31,30168,9284,20884,53.00,57.00,53057,2020
15039,lifesat,-0.12,0.24,0.29,24816,7200,17616,55.00,131.00,55131,2020
15040,lifesat,0.02,0.70,0.27,1603,433,1170,56.00,15.00,56015,2020
15043,lifesat,-0.09,0.50,0.31,3885,1249,2636,8.00,83.00,08083,2020
15450,lifesat,-0.22,0.65,0.31,1916,552,1364,12.00,79.00,12079,2020
15760,lifesat,-0.06,0.09,0.28,329739,93290,236449,17.00,43.00,17043,2021
15761,lifesat,-0.08,0.55,0.31,2898,871,2027,24.00,29.00,24029,2021
15762,lifesat,-0.07,0.42,0.28,7534,2135,5399,40.00,51.00,40051,2021
15763,lifesat,-0.03,0.27,0.30,21109,6256,14853,53.00,75.00,53075,2021
15764,lifesat,-0.04,0.73,0.28,1735,497,1238,40.00,9.00,40009,2021
16144,lifesat,-0.16,0.79,0.27,598,169,429,27.00,135.00,27135,2021
16408,lifesat,-0.05,0.11,0.27,169458,46428,123030,17.00,197.00,17197,2022
16409,lifesat,-0.01,0.49,0.26,5040,1314,3726,19.00,187.00,19187,2022
16410,lifesat,-0.00,0.71,0.21,938,227,711,19.00,183.00,19183,2022
16411,lifesat,-0.08,0.29,0.29,16863,4925,11938,21.00,185.00,21185,2022
16412,lifesat,-0.11,0.29,0.26,18926,5004,13922,20.00,103.00,20103,2022
16413,lifesat,-0.11,0.06,0.29,1270490,365006,905484,36.00,81.00,36081,2022
16414,lifesat,-0.03,0.39,0.29,8343,2360,5983,49.00,51.00,49051,2022
16415,lifesat,0.01,0.35,0.27,11765,3210,8555,55.00,111.00,55111,2022
16416,lifesat,-0.09,0.80,0.31,1126,338,788,48.00,427.00,48427,2022
16417,lifesat,0.03,0.27,0.28,19099,5388,13711,37.00,31.00,37031,2022
16759,lifesat,0.17,0.77,0.28,1024,281,743,47.00,23.00,47023,2022
17180,lifesat,-0.31,0.34,0.26,5459,1411,4048,36.00,79.00,36079,2023
17181,lifesat,-0.15,0.31,0.27,8959,2393,6566,39.00,43.00,39043,2023
17182,lifesat,-0.07,0.44,0.25,3151,814,2337,39.00,169.00,39169,2023
17183,lifesat,0.07,0.23,0.29,12792,3660,9132,47.00,125.00,47125,2023
17185,lifesat,-0.03,0.60,0.30,1577,456,1121,40.00,21.00,40021,2023
18421,lifesat,-0.02,0.20,0.33,24245,7948,16297,12.00,95.00,12095,2012
18422,lifesat,-0.19,0.29,0.33,9131,3076,6055,24.00,3.00,24003,2012
18424,lifesat,-0.32,0.73,0.36,502,175,327,17.00,99.00,17099,2012
18425,lifesat,-0.16,0.70,0.37,1227,437,790,39.00,119.00,39119,2012
18617,lifesat,-0.17,0.54,0.34,1747,607,1140,26.00,73.00,26073,2012
18688,lifesat,-0.18,0.77,0.36,568,198,370,42.00,103.00,42103,2012
19161,lifesat,-0.16,0.10,0.37,99297,37234,62063,23.00,19.00,23019,2013
19162,lifesat,-0.16,0.13,0.36,42348,15392,26956,18.00,109.00,18109,2013
19163,lifesat,-0.24,0.07,0.36,268787,96676,172111,39.00,103.00,39103,2013
19164,lifesat,-0.16,0.11,0.36,94527,33823,60704,55.00,127.00,55127,2013
19165,lifesat,-0.12,0.05,0.35,1634686,572202,1062484,27.00,53.00,27053,2013
19480,lifesat,-0.17,0.34,0.37,5898,2175,3723,20.00,189.00,20189,2013
19481,lifesat,-0.19,0.20,0.36,19398,6874,12524,20.00,151.00,20151,2013
19482,lifesat,-0.11,0.13,0.36,56698,20311,36387,35.00,49.00,35049,2013
19483,lifesat,-0.20,0.21,0.36,15982,5710,10272,48.00,387.00,48387,2013
19484,lifesat,-0.10,0.15,0.37,35552,13018,22534,49.00,21.00,49021,2013
19485,lifesat,-0.15,0.31,0.37,6925,2453,4472,21.00,77.00,21077,2013
19486,lifesat,-0.27,0.38,0.35,5312,1768,3544,29.00,135.00,29135,2013
20034,lifesat,-0.15,0.05,0.35,621780,219417,402363,6.00,47.00,06047,2014
20035,lifesat,-0.21,0.09,0.36,137846,48707,89139,22.00,115.00,22115,2014
20036,lifesat,-0.24,0.13,0.35,79269,27799,51470,24.00,39.00,24039,2014
20037,lifesat,-0.19,0.25,0.37,16508,6051,10457,27.00,113.00,27113,2014
20038,lifesat,-0.11,0.20,0.37,30261,10851,19410,28.00,115.00,28115,2014
20039,lifesat,-0.13,0.08,0.37,508301,189051,319250,33.00,15.00,33015,2014
20040,lifesat,-0.14,0.10,0.36,138454,50265,88189,36.00,77.00,36077,2014
20041,lifesat,-0.21,0.09,0.37,163326,60512,102814,39.00,147.00,39147,2014
20042,lifesat,-0.12,0.19,0.36,29384,10570,18814,40.00,9.00,40009,2014
20043,lifesat,-0.19,0.24,0.38,18067,6860,11207,54.00,85.00,54085,2014
20044,lifesat,-0.05,0.56,0.36,2474,893,1581,48.00,243.00,48243,2014
20045,lifesat,-0.10,0.37,0.39,6701,2641,4060,54.00,93.00,54093,2014
20983,lifesat,-0.07,0.28,0.21,43066,11423,31643,2.00,170.00,02170,2015
20984,lifesat,0.03,0.40,0.28,7753,2653,5100,8.00,3.00,08003,2015
20985,lifesat,-0.03,0.55,0.28,1286,384,902,13.00,315.00,13315,2015
20986,lifesat,-0.13,0.50,0.29,3654,1231,2423,17.00,51.00,17051,2015
20987,lifesat,-0.06,0.37,0.29,9162,3178,5984,17.00,55.00,17055,2015
20988,lifesat,-0.06,0.29,0.29,12820,4473,8347,18.00,183.00,18183,2015
20989,lifesat,0.01,0.29,0.26,12482,4184,8298,27.00,119.00,27119,2015
20990,lifesat,-0.08,0.21,0.28,48475,16063,32412,41.00,43.00,41043,2015
20991,lifesat,-0.09,0.57,0.32,1751,603,1148,48.00,267.00,48267,2015
20992,lifesat,-0.12,0.40,0.27,4303,1490,2813,13.00,161.00,13161,2015
20993,lifesat,-0.06,0.45,0.26,4360,1421,2939,40.00,63.00,40063,2015
20994,lifesat,0.15,0.65,0.34,1417,469,948,49.00,55.00,49055,2015
20995,lifesat,-0.01,0.60,0.27,881,290,591,40.00,59.00,40059,2015
20996,lifesat,0.01,0.54,0.29,1244,419,825,31.00,23.00,31023,2015
21121,lifesat,0.05,0.69,0.30,933,309,624,29.00,185.00,29185,2015
21179,lifesat,0.66,0.15,0.20,67051,13143,53908,45.00,19.00,45019,2016
21180,lifesat,0.61,0.18,0.21,40966,8480,32486,47.00,93.00,47093,2016
21181,lifesat,0.65,0.30,0.21,13510,2884,10626,23.00,31.00,23031,2016
21182,lifesat,0.49,0.53,0.16,5606,888,4718,39.00,157.00,39157,2016
21183,lifesat,0.32,0.51,0.17,8882,1331,7551,34.00,41.00,34041,2016
21299,lifesat,0.66,0.57,0.18,1881,322,1559,47.00,63.00,47063,2016
21300,lifesat,0.50,0.47,0.21,6345,1275,5070,56.00,21.00,56021,2016
21428,lifesat,0.65,0.69,0.11,865,105,760,20.00,121.00,20121,2016
21429,lifesat,0.46,0.76,0.18,543,103,440,28.00,91.00,28091,2016
21968,lifesat,0.54,0.22,0.17,45067,7592,37475,17.00,167.00,17167,2017
21969,lifesat,0.54,0.58,0.14,4066,605,3461,40.00,111.00,40111,2017
21970,lifesat,0.52,0.22,0.17,35616,6151,29465,39.00,57.00,39057,2017
21971,lifesat,0.63,0.64,0.18,1949,341,1608,51.00,145.00,51145,2017
21972,lifesat,0.53,0.57,0.16,4258,677,3581,22.00,89.00,22089,2017
21973,lifesat,0.46,0.85,0.17,519,93,426,27.00,133.00,27133,2017
21974,lifesat,0.42,0.37,0.19,13008,2486,10522,28.00,121.00,28121,2017
21975,lifesat,0.66,0.24,0.15,19603,2869,16734,5.00,131.00,05131,2017
21976,lifesat,0.61,0.61,0.13,2137,277,1860,20.00,59.00,20059,2017
21977,lifesat,0.62,0.42,0.16,7186,1128,6058,17.00,183.00,17183,2017
21978,lifesat,0.63,0.61,0.13,3229,417,2812,29.00,9.00,29009,2017
21980,lifesat,0.68,0.62,0.10,1143,121,1022,19.00,165.00,19165,2017

In [24]:
df = df[df['year'] <= 2019] #drop covid years

so have 12-19 just 8yrs reasonable to take avg and then get pop siz and density for mid yr ie 2016 (closer to 19 fine bc 12 had fewer obs)